version: '3.8'

services:
  rent-app:
    build: .
    container_name: rent-management-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount data directory for persistent CSV storage
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - rent-network

networks:
  rent-network:
    driver: bridge 